const CHANGING_SEARCH_TEXT = "CHANGING_SEARCH_TEXT"

// COLLEGES
const LOADING_COLLEGES = "LOADING_COLLEGES" 
const FETCHED_COLLEGES = "FETCHED_COLLEGES"




export { LOADING_COLLEGES, FETCHED_COLLEGES,
CHANGING_SEARCH_TEXT} 
